apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-policy-engine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-policy-engine.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      serviceAccountName: {{ include "kube-policy-engine.fullname" . }}
      app.kubernetes.io/name: {{ include "kube-policy-engine.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-policy-engine.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: webhook
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: {{ include "kube-policy-engine.fullname" . }}-cert
